package model;

import java.util.ArrayList;

/**
 * Represents a strongly connected service as generated by identifySCS
 *
 */
public class StronglyConnectedService 
{
	public int index;
	public ArrayList<ServiceNode> nodes;
	
	/**
	 * Construct service with defined index in the SCS
	 * @param index The index of the service in the SCS
	 */
	public StronglyConnectedService(int index) 
	{
		this.index = index;
		nodes = new ArrayList<ServiceNode>();
	}
	
	/**
	 * @return the index of the service
	 */
	public int getIndex()
	{
		return index;
	}

	/**
	 * @param w {@link serviceNode} to be added
	 */
	public void add(ServiceNode w) 
	{
		nodes.add(w);
	}

	public ArrayList<ServiceNode> getServiceNodes() 
	{
		return nodes;
	}

	// Check all of our essential services and see if any of them has an input that matches the one given
	public boolean hasInput(String input) 
	{
		for (ServiceNode sn : nodes)
		{
			if (sn.getService().getInputService().contains(input))
			{
				return true;
			}
		}
		return false;
	}
	
	// Check all of our essential services and see if any of them has an output that matches the one given
	public boolean hasOutput(String output) 
	{
		for (ServiceNode sn : nodes)
		{
			if (sn.getService().getOutputService().contains(output))
			{
				return true;
			}
		}
		return false;
	}

	// Compiles a list of all of the inputs to all of the essential services in me
	public ArrayList<IOVariable> getAllInputs() 
	{
		ArrayList<IOVariable> inputs = new ArrayList<IOVariable>();
		
		for (ServiceNode sn : nodes)
		{
			for (IOVariable input : sn.getService().getInputService())
			{
				// Avoid duplicates
				if (!inputs.contains(input))
				{
					inputs.add(input);
				}
			}
		}
		
		return inputs;
	}

	// Compiles a list of all of the outputs from all of the essential services in me
	public ArrayList<IOVariable> getAllOutputs() 
	{
		ArrayList<IOVariable> outputs = new ArrayList<IOVariable>();
		
		for (ServiceNode sn : nodes)
		{
			for (IOVariable output : sn.getService().getOutputService())
			{
				// Avoid duplicates
				if (!outputs.contains(output))
				{
					outputs.add(output);
				}
			}
		}
		
		return outputs;
	}
	
	// Returns a list of all dataflows that are connected to this SCS (but not internal ones)
		public ArrayList<IOVariable> getDataFlows() 
		{
			ArrayList<IOVariable> dataFlows = new ArrayList<IOVariable>();
			
			// First get all the inputs and outputs for every elementary sub-service
			ArrayList<IOVariable> allInputs = getAllInputs();
			ArrayList<IOVariable> allOutputs = getAllOutputs();
			
			// To avoid internal flows, only add inputs that are not also outputs
			for (IOVariable output : allOutputs)
			{
				if (!allInputs.contains(output))
				{
					dataFlows.add(output);
				}
			}
			
			// To avoid internal flows, only add outputs that are not also inputs
			for (IOVariable input : allInputs)
			{
				if (!allOutputs.contains(input))
				{
					dataFlows.add(input);
				}
			}
			
			return dataFlows;
		}
		
	}


