import java.util.ArrayList;

/**
 * 
 */

/**
 * @author jordan
 * class designed to be used as a tuple in the GenerateL1 method
 * everything is public because why not? there's no need for encapsulation on this
 * it's just a simple block of data to keep things neat
 */

public class L1Tuple 
{
	//"Main Service", "Sub Service", "inputs", "outputs", "name of variable",
	//"inputs  variable", "outputs variable"
	public String mainService;
	public ArrayList<String> subServices;
	public ArrayList<String> inputs;
	public ArrayList<String> outputs;
	public String nameOfVariable;
	public ArrayList<String> inputsVariables;
	public ArrayList<String> outputsVariables;
	
	//autogenerated constructors
	public L1Tuple(){}

	public L1Tuple(String mainService, ArrayList<String> subServices, ArrayList<String> inputs,
			ArrayList<String> outputs, String nameOfVariable, ArrayList<String> inputsVariables,
			ArrayList<String> outputsVariables) 
	{
		super();
		this.mainService = mainService;
		this.subServices = subServices;
		this.inputs = inputs;
		this.outputs = outputs;
		this.nameOfVariable = nameOfVariable;
		this.inputsVariables = inputsVariables;
		this.outputsVariables = outputsVariables;
	}
	
}
